<?php

// Automatically generated from json files and roles.txt. Do not edit directly.

$rolesMatrix = array (
  'Administrative' => 
  array (
    0 => 'Administrative Assistant',
    1 => 'Assistant',
    2 => 'Assistant Administrative',
    3 => 'Assistant Manager',
    4 => 'Clerk',
    5 => 'Executive Assistant',
    6 => 'Office Administrator',
    7 => 'Office Assistant',
    8 => 'Office Clerk',
    9 => 'Office Coordinator',
    10 => 'Office Manager',
    11 => 'Office Representative',
    12 => 'Personal Assistant',
    13 => 'Program Assistant',
    14 => 'Receptionist',
    15 => 'Scheduling Coordinator',
    16 => 'Service Assistant',
    17 => 'Service Coordinator',
    18 => 'Service Manager',
    19 => 'Services Director',
    20 => 'Unit Secretary',
  ),
  'Business Operations, HR & Executive' => 
  array (
    0 => 'Business Analyst',
    1 => 'Business Development Manager',
    2 => 'Business Manager',
    3 => 'CFO',
    4 => 'Consultant',
    5 => 'Director Assistant',
    6 => 'Executive',
    7 => 'General Manager',
    8 => 'HR Generalist',
    9 => 'HR Manager',
    10 => 'HR Specialist',
    11 => 'Manager',
    12 => 'Manager Assistant',
    13 => 'Operations Associate',
    14 => 'Operations Coordinator',
    15 => 'Operations Manager',
    16 => 'Operations Supervisor',
    17 => 'Payroll Specialist',
    18 => 'Product Manager',
    19 => 'Program Coordinator',
    20 => 'Program Director',
    21 => 'Program Manager',
    22 => 'Program Specialist',
    23 => 'Project Coordinator',
    24 => 'Project Manager',
    25 => 'Recruiter',
    26 => 'Recruitment Manager',
    27 => 'Regional Director',
    28 => 'Regional Manager',
    29 => 'Relationship Manager',
    30 => 'Safety Manager',
    31 => 'Safety Specialist',
    32 => 'Senior Analyst',
    33 => 'Senior Director',
    34 => 'Senior Project Manager',
    35 => 'Team Manager',
    36 => 'Training Manager',
    37 => 'Training Specialist',
    38 => 'Vice President',
  ),
  'Construction, Manufacturing & Trades' => 
  array (
    0 => 'Architect',
    1 => 'Assembler',
    2 => 'Auto Mechanic',
    3 => 'Automotive Mechanic',
    4 => 'Automotive Technician',
    5 => 'Carpenter',
    6 => 'CNC Machinist',
    7 => 'CNC Operator',
    8 => 'CNC Programmer',
    9 => 'Construction Manager',
    10 => 'Construction Project Manager',
    11 => 'Construction Superintendent',
    12 => 'Construction Worker',
    13 => 'Diesel Mechanic',
    14 => 'Electrician',
    15 => 'Environmental Officer',
    16 => 'Estimator',
    17 => 'General Laborer',
    18 => 'Handyworker',
    19 => 'Heavy Equipment Operator',
    20 => 'HVAC Installer',
    21 => 'HVAC Service Technician',
    22 => 'HVAC Technician',
    23 => 'Journeyman Electrician',
    24 => 'Laborer',
    25 => 'Landscape Worker',
    26 => 'Machine Operator',
    27 => 'Maintenance Manager',
    28 => 'Maintenance Supervisor',
    29 => 'Material Handler',
    30 => 'Nanny',
    31 => 'Painter',
    32 => 'Pest Control Technician',
    33 => 'Pet Sitter',
    34 => 'Product Engineer',
    35 => 'Production Associate',
    36 => 'Production Manager',
    37 => 'Production Operator',
    38 => 'Production Supervisor',
    39 => 'Production Worker',
    40 => 'Quality Assurance Analyst',
    41 => 'Quality Assurance Engineer',
    42 => 'Quality Assurance Inspector',
    43 => 'Quality Assurance Manager',
    44 => 'Quality Assurance Specialist',
    45 => 'Quality Control Manager',
    46 => 'Repair Technician',
    47 => 'Sanitation Worker',
    48 => 'Senior Technician',
    49 => 'Service Advisor',
    50 => 'Site Manager',
    51 => 'Superintendent',
    52 => 'Utility Worker',
    53 => 'Welder',
  ),
  'Customer Service & Hospitality' => 
  array (
    0 => 'Barista',
    1 => 'Bartender',
    2 => 'Call Center Representative',
    3 => 'Chef',
    4 => 'Cleaner',
    5 => 'Cook',
    6 => 'Customer Service',
    7 => 'Customer Service Representative',
    8 => 'Dishwasher',
    9 => 'Executive Chef',
    10 => 'Front Desk Receptionist',
    11 => 'Hostess',
    12 => 'Hotel Manager',
    13 => 'Housekeeper',
    14 => 'Kitchen Manager',
    15 => 'Parking Attendant',
    16 => 'Porter',
    17 => 'Prep Cook',
    18 => 'Restaurant Manager',
    19 => 'Restaurant Team Member',
    20 => 'Room Attendant',
    21 => 'Senior Customer Service Representative',
    22 => 'Server',
    23 => 'Special Events Manager',
  ),
  'Education' => 
  array (
    0 => 'School Teacher',
    1 => 'Special Education Teacher',
    2 => 'Student Assistant',
    3 => 'Substitute Teacher',
    4 => 'Teacher',
    5 => 'Teaching Assistant',
    6 => 'Tutor',
  ),
  'Finance & Accounting' => 
  array (
    0 => 'Accountant',
    1 => 'Accounting Clerk',
    2 => 'Accounts Payable Specialist',
    3 => 'Accounts Receivable Specialist',
    4 => 'Banker',
    5 => 'Bookkeeper',
    6 => 'Branch Manager',
    7 => 'Controller',
    8 => 'Cost Accountant',
    9 => 'CPA',
    10 => 'Finance Manager',
    11 => 'Financial Advisor',
    12 => 'Financial Analyst',
    13 => 'Insurance Agent',
    14 => 'Insurance Sales',
    15 => 'Loan Officer',
    16 => 'Risk Manager',
    17 => 'Senior Financial Analyst',
    18 => 'Teller',
  ),
  'Government, Legal & Public Safety' => 
  array (
    0 => 'Attorney',
    1 => 'Law Enforcement Officer',
    2 => 'Legal Assistant',
    3 => 'Legal Secretary',
    4 => 'Paralegal',
    5 => 'Police Officer',
    6 => 'Public Safety Officer',
    7 => 'Security Guard',
    8 => 'Security Officer',
    9 => 'Security Specialist',
  ),
  'Healthcare & Personal Care' => 
  array (
    0 => 'Beauty Therapist',
    1 => 'Care Assistant',
    2 => 'Caregiver',
    3 => 'Case Manager',
    4 => 'Certified Medical Assistant',
    5 => 'Certified Nursing Assistant',
    6 => 'Cosmetologist',
    7 => 'Counselor',
    8 => 'Dental Assistant',
    9 => 'Dental Hygienist',
    10 => 'Dental Receptionist',
    11 => 'Dentist',
    12 => 'Director of Nursing',
    13 => 'Esthetician',
    14 => 'Hair Stylist',
    15 => 'Home Health Aide',
    16 => 'Lab Technician',
    17 => 'Licensed Practical Nurse',
    18 => 'Massage Therapist',
    19 => 'Medical Assistant',
    20 => 'Medical Billing Specialist',
    21 => 'Medical Receptionist',
    22 => 'Nurse Practitioner',
    23 => 'Nursing Assistant',
    24 => 'Nursing Case Manager',
    25 => 'Occupational Therapist',
    26 => 'Operating Nurse',
    27 => 'Patient Access Manager',
    28 => 'Patient Assistant',
    29 => 'Patient Coordinator',
    30 => 'Patient Service Representative',
    31 => 'Pharmacist',
    32 => 'Pharmacy Technician',
    33 => 'Phlebotomist',
    34 => 'Physical Therapist Assistant',
    35 => 'Physical Therapy Aide',
    36 => 'Physician',
    37 => 'Physician Assistant',
    38 => 'Registered Nurse',
    39 => 'Research Assistant',
    40 => 'Resident Assistant',
    41 => 'Social Worker',
    42 => 'Speech Language Pathologist',
    43 => 'Sterile Processing Technician',
    44 => 'Substance Abuse Counselor',
    45 => 'Surgical Nurse',
    46 => 'Surgical Technician',
    47 => 'Technician',
    48 => 'Therapist',
    49 => 'Trainer',
    50 => 'Veterinary Assistant',
    51 => 'Veterinary Receptionist',
    52 => 'Veterinary Technician',
    53 => 'X-Ray Technician',
  ),
  'Marketing, Media & Design' => 
  array (
    0 => 'Designer',
    1 => 'Digital Marketing Specialist',
    2 => 'Director Marketing',
    3 => 'Editor',
    4 => 'Graphic Design',
    5 => 'Interior Designer',
    6 => 'Marketing',
    7 => 'Marketing Coordinator',
    8 => 'Marketing Manager',
    9 => 'Outreach Coordinator',
    10 => 'Photographer',
    11 => 'Producer',
    12 => 'Product Specialist',
    13 => 'Production Assistant',
    14 => 'Sales and Marketing Manager',
    15 => 'Social Media Intern',
    16 => 'Social Media Specialist',
  ),
  'Retail, Sales & Real Estate' => 
  array (
    0 => 'Account Executive',
    1 => 'Assistant Store Manager',
    2 => 'Buyer',
    3 => 'Car Sales',
    4 => 'Cashier',
    5 => 'Cashier Customer Service',
    6 => 'Director Sales',
    7 => 'District Manager',
    8 => 'Inside Sales',
    9 => 'Leasing Consultant',
    10 => 'Merchandiser',
    11 => 'Outside Sales Rep',
    12 => 'Packer',
    13 => 'Property Manager',
    14 => 'Real Estate Agent',
    15 => 'Real Estate Manager',
    16 => 'Regional Sales Manager',
    17 => 'Retail Assistant Manager',
    18 => 'Retail Associate',
    19 => 'Retail Manager',
    20 => 'Retail Merchandiser',
    21 => 'Route Sales Representative',
    22 => 'Sales Associate',
    23 => 'Sales Consultant',
    24 => 'Sales Director',
    25 => 'Sales Manager',
    26 => 'Sales Professional',
    27 => 'Sales Representative',
    28 => 'Sales Specialist',
    29 => 'Sales Support Representative',
    30 => 'Seasonal Associate',
    31 => 'Shift Leader',
    32 => 'Shift Manager',
    33 => 'Stock Associate',
    34 => 'Stocker',
    35 => 'Store Clerk',
    36 => 'Team Member',
    37 => 'Telemarketing',
    38 => 'Territory Manager',
  ),
  'Technology & Engineering' => 
  array (
    0 => 'Android Developer',
    1 => 'Chemist',
    2 => 'Civil Engineer',
    3 => 'Data Analyst',
    4 => 'Data Entry Clerk',
    5 => 'Data Scientist',
    6 => 'Desktop Support',
    7 => 'DevOps Engineer',
    8 => 'Electrical Engineer',
    9 => 'Electrical Engineering',
    10 => 'Embedded Software Engineer',
    11 => 'Front End Developer',
    12 => 'Hadoop Developer',
    13 => 'Help Desk Associate',
    14 => 'IOS Developer',
    15 => 'IT',
    16 => 'IT Project Manager',
    17 => 'Java Developer',
    18 => 'Linux Administrator',
    19 => 'Mechanical Engineer',
    20 => 'Operations Analyst',
    21 => 'Process Engineer',
    22 => 'Program Analyst',
    23 => 'Research Associate',
    24 => 'Senior Engineer',
    25 => 'Service Technician',
    26 => 'Software Architect',
    27 => 'Software Developer',
    28 => 'Software Engineer',
    29 => 'Support Specialist',
    30 => 'System Engineer',
    31 => 'Systems Administrator',
    32 => 'Systems Analyst',
    33 => 'Technical Program Manager',
    34 => 'Technical Writer',
    35 => 'Technologist',
  ),
  'Transportation & Logistics' => 
  array (
    0 => 'CDL Driver',
    1 => 'Delivery Driver',
    2 => 'Dispatcher',
    3 => 'Forklift Operator',
    4 => 'Logistics Specialist',
    5 => 'Order Picker',
    6 => 'Package Handler',
    7 => 'Receiving Associate',
    8 => 'Replenishment Associate',
    9 => 'Route Driver',
    10 => 'Rural Carrier Associate',
    11 => 'Secretary Warehouse Manager',
    12 => 'Shipping and Receiving Clerk',
    13 => 'Shuttle Driver',
    14 => 'Supply Chain Manager',
    15 => 'Transporter',
    16 => 'Truck Driver',
    17 => 'Unloader',
    18 => 'Van Driver',
    19 => 'Warehouse Clerk',
    20 => 'Warehouse Delivery Driver',
    21 => 'Warehouse Supervisor',
    22 => 'Warehouse Worker',
  ),
);

$fieldDescriptions = array (
  'Administrative' => 'Administrative roles support daily office operations through organization, communication and coordination. Strong resumes in this field often highlight skills like scheduling, document management and customer communication.',
  'Business Operations, HR & Executive' => 'Business operations, human resources and executive roles help organizations run effectively by guiding people, processes and strategy. Resumes in this area typically feature leadership abilities, process improvement experience and talent management skills.',
  'Construction, Manufacturing & Trades' => 'Construction, manufacturing and trade careers involve building, repairing and maintaining structures, equipment and products. Relevant skills to highlight may include equipment operation, safety compliance and hands-on technical expertise.',
  'Customer Service & Hospitality' => 'Customer service and hospitality roles focus on engaging with customers, resolving questions and creating positive experiences. Resumes often emphasize communication, conflict resolution and fast-paced service skills.',
  'Education' => 'Education professionals teach, mentor and support students in various learning environments. Skills such as lesson planning, classroom management and student assessment are commonly featured.',
  'Finance & Accounting' => 'Finance and accounting roles center on analyzing data, managing budgets and ensuring accurate records. Key skills may include financial reporting, data analysis and proficiency with accounting software.',
  'Government, Legal & Public Safety' => 'Government, legal and public safety roles serve communities through regulation, protection and public service. Resumes often highlight policy knowledge, case documentation and incident response skills.',
  'Healthcare & Personal Care' => 'Healthcare and personal care careers support patient well-being through clinical care, treatment and daily assistance. Important skills include patient communication, medical terminology knowledge and clinical procedures.',
  'Marketing, Media & Design' => 'Marketing, media and design professionals create content, develop campaigns and communicate ideas through various formats. Common skills to showcase include content creation, audience analysis and design software proficiency.',
  'Retail, Sales & Real Estate' => 'Retail, sales and real estate roles help people find products, services or properties that meet their needs. Useful skills to highlight include customer engagement, product knowledge and sales strategy.',
  'Technology & Engineering' => 'Technology and engineering roles involve designing, building and maintaining systems, software or technical solutions. Skills such as programming, troubleshooting and project management are often central.',
  'Transportation & Logistics' => 'Transportation and logistics professionals ensure products and people move safely and efficiently. Resumes in this field often feature inventory management, route planning and equipment operation skills.',
);

$fieldMatrices = array (
  'Administrative' => 
  array (
    'core' => 
    array (
      0 => 'office suite',
      1 => 'ms office',
      2 => 'excel',
      3 => 'word',
      4 => 'calendar',
      5 => 'scheduling',
      6 => 'billing',
      7 => 'data entry',
    ),
    'supporting' => 
    array (
      0 => 'customer service',
      1 => 'organization',
      2 => 'filing',
      3 => 'bookkeeping',
      4 => 'phone',
      5 => 'reception',
      6 => 'meetings',
    ),
  ),
  'Business Operations, HR & Executive' => 
  array (
    'core' => 
    array (
      0 => 'operations',
      1 => 'project management',
      2 => 'agile',
      3 => 'hris',
      4 => 'payroll',
      5 => 'budgeting',
      6 => 'recruitment',
      7 => 'onboarding',
    ),
    'supporting' => 
    array (
      0 => 'leadership',
      1 => 'strategy',
      2 => 'process improvement',
      3 => 'scrum',
      4 => 'jira',
      5 => 'policy',
      6 => 'analytics',
    ),
  ),
  'Construction, Manufacturing & Trades' => 
  array (
    'core' => 
    array (
      0 => 'osha',
      1 => 'safety',
      2 => 'blueprints',
      3 => 'maintenance',
      4 => 'troubleshooting',
      5 => 'welding',
      6 => 'hvac',
      7 => 'cad',
    ),
    'supporting' => 
    array (
      0 => 'quality assurance',
      1 => 'inspections',
      2 => 'hand tools',
      3 => 'repairs',
      4 => 'inventory',
      5 => 'machinery',
    ),
  ),
  'Customer Service & Hospitality' => 
  array (
    'core' => 
    array (
      0 => 'pos',
      1 => 'crm',
      2 => 'ticketing',
      3 => 'billing',
      4 => 'reservations',
      5 => 'cashier',
      6 => 'phone support',
      7 => 'escalations',
    ),
    'supporting' => 
    array (
      0 => 'communication',
      1 => 'problem solving',
      2 => 'multitasking',
      3 => 'hospitality',
      4 => 'satisfaction',
      5 => 'inquiries',
    ),
  ),
  'Education' => 
  array (
    'core' => 
    array (
      0 => 'curriculum',
      1 => 'lesson plan',
      2 => 'assessment',
      3 => 'classroom management',
      4 => 'iep',
      5 => 'tutoring',
      6 => 'pedagogy',
    ),
    'supporting' => 
    array (
      0 => 'mentoring',
      1 => 'communication',
      2 => 'instruction',
      3 => 'grading',
      4 => 'collaboration',
      5 => 'e-learning',
    ),
  ),
  'Finance & Accounting' => 
  array (
    'core' => 
    array (
      0 => 'gaap',
      1 => 'quickbooks',
      2 => 'general ledger',
      3 => 'auditing',
      4 => 'tax preparation',
      5 => 'reconciliation',
      6 => 'financial statements',
      7 => 'excel',
    ),
    'supporting' => 
    array (
      0 => 'cpa',
      1 => 'forecasting',
      2 => 'accounts payable',
      3 => 'accounts receivable',
      4 => 'compliance',
      5 => 'ledger',
      6 => 'sap',
    ),
  ),
  'Government, Legal & Public Safety' => 
  array (
    'core' => 
    array (
      0 => 'litigation',
      1 => 'legal research',
      2 => 'compliance',
      3 => 'security',
      4 => 'investigation',
      5 => 'contract',
      6 => 'policy',
      7 => 'documentation',
    ),
    'supporting' => 
    array (
      0 => 'writing',
      1 => 'confidentiality',
      2 => 'reporting',
      3 => 'patrol',
      4 => 'emergency',
      5 => 'regulation',
      6 => 'risk',
    ),
  ),
  'Healthcare & Personal Care' => 
  array (
    'core' => 
    array (
      0 => 'hipaa',
      1 => 'ehr',
      2 => 'emr',
      3 => 'patient care',
      4 => 'cpr',
      5 => 'bls',
      6 => 'clinical',
      7 => 'medical terminology',
    ),
    'supporting' => 
    array (
      0 => 'medication',
      1 => 'vital signs',
      2 => 'triage',
      3 => 'assessment',
      4 => 'nursing',
      5 => 'therapy',
      6 => 'hygiene',
    ),
  ),
  'Marketing, Media & Design' => 
  array (
    'core' => 
    array (
      0 => 'seo',
      1 => 'sem',
      2 => 'google analytics',
      3 => 'social media',
      4 => 'content strategy',
      5 => 'adobe',
      6 => 'photoshop',
      7 => 'illustrator',
    ),
    'supporting' => 
    array (
      0 => 'branding',
      1 => 'email marketing',
      2 => 'copywriting',
      3 => 'graphic design',
      4 => 'campaigns',
      5 => 'marketing automation',
    ),
  ),
  'Retail, Sales & Real Estate' => 
  array (
    'core' => 
    array (
      0 => 'crm',
      1 => 'salesforce',
      2 => 'lead generation',
      3 => 'cold calling',
      4 => 'negotiation',
      5 => 'pipeline',
      6 => 'retail',
      7 => 'leasing',
    ),
    'supporting' => 
    array (
      0 => 'relationship building',
      1 => 'closing',
      2 => 'prospecting',
      3 => 'customer relationship',
      4 => 'account management',
      5 => 'presentations',
    ),
  ),
  'Technology & Engineering' => 
  array (
    'core' => 
    array (
      0 => 'software',
      1 => 'programming',
      2 => 'sql',
      3 => 'git',
      4 => 'database',
      5 => 'cloud',
      6 => 'architecture',
      7 => 'api',
      8 => 'agile',
    ),
    'supporting' => 
    array (
      0 => 'debugging',
      1 => 'testing',
      2 => 'linux',
      3 => 'bash',
      4 => 'cicd',
      5 => 'microservices',
      6 => 'scrum',
    ),
  ),
  'Transportation & Logistics' => 
  array (
    'core' => 
    array (
      0 => 'inventory',
      1 => 'shipping',
      2 => 'receiving',
      3 => 'wms',
      4 => 'forklift',
      5 => 'cdl',
      6 => 'logistics',
      7 => 'dispatch',
    ),
    'supporting' => 
    array (
      0 => 'safety',
      1 => 'routing',
      2 => 'manifest',
      3 => 'tracking',
      4 => 'supply chain',
      5 => 'warehouse',
    ),
  ),
);

$roleMatrices = array (
  'Java Developer' => 
  array (
    'core' => 
    array (
      0 => 'java',
      1 => 'spring',
      2 => 'spring boot',
      3 => 'hibernate',
      4 => 'maven',
      5 => 'gradle',
      6 => 'junit',
      7 => 'jpa',
      8 => 'jdbc',
      9 => 'multithreading',
      10 => 'concurrency',
    ),
    'supporting' => 
    array (
      0 => 'sql',
      1 => 'rest',
      2 => 'api',
      3 => 'git',
      4 => 'docker',
      5 => 'microservices',
      6 => 'tomcat',
      7 => 'databases',
      8 => 'web technologies',
      9 => 'testing',
      10 => 'scrum',
      11 => 'agile',
      12 => 'backbone',
      13 => 'security',
    ),
  ),
  'Senior Engineer' => 
  array (
    'core' => 
    array (
      0 => 'engineering',
      1 => 'design',
      2 => 'python',
      3 => 'java',
      4 => 'javascript',
      5 => 'software',
      6 => 'programming',
      7 => 'architecture',
      8 => 'development',
    ),
    'supporting' => 
    array (
      0 => 'cad',
      1 => 'inspection',
      2 => 'safety',
      3 => 'project management',
      4 => 'agile',
      5 => 'git',
      6 => 'testing',
      7 => 'debugging',
      8 => 'osha',
    ),
  ),
  'Android Developer' => 
  array (
    'core' => 
    array (
      0 => 'android',
      1 => 'kotlin',
      2 => 'java',
      3 => 'sdk',
      4 => 'gradle',
      5 => 'retrofit',
      6 => 'jetpack compose',
      7 => 'android studio',
    ),
    'supporting' => 
    array (
      0 => 'git',
      1 => 'api',
      2 => 'xml',
      3 => 'mvvm',
      4 => 'sqlite',
      5 => 'rxjava',
      6 => 'coroutine',
      7 => 'testing',
    ),
  ),
  'IOS Developer' => 
  array (
    'core' => 
    array (
      0 => 'ios',
      1 => 'swift',
      2 => 'objective-c',
      3 => 'xcode',
      4 => 'cocoapods',
      5 => 'swiftui',
      6 => 'core data',
      7 => 'combine',
    ),
    'supporting' => 
    array (
      0 => 'git',
      1 => 'api',
      2 => 'mvvm',
      3 => 'core data',
      4 => 'testing',
      5 => 'jenkins',
      6 => 'testflight',
    ),
  ),
  'DevOps Engineer' => 
  array (
    'core' => 
    array (
      0 => 'devops',
      1 => 'terraform',
      2 => 'kubernetes',
      3 => 'docker',
      4 => 'jenkins',
      5 => 'ci/cd',
      6 => 'aws',
      7 => 'gcp',
      8 => 'azure',
      9 => 'pipelines',
    ),
    'supporting' => 
    array (
      0 => 'linux',
      1 => 'bash',
      2 => 'ansible',
      3 => 'git',
      4 => 'nginx',
      5 => 'helm',
      6 => 'prometheus',
      7 => 'grafana',
      8 => 'vault',
    ),
  ),
  'Front End Developer' => 
  array (
    'core' => 
    array (
      0 => 'react',
      1 => 'javascript',
      2 => 'typescript',
      3 => 'next\\.js',
      4 => 'vue',
      5 => 'angular',
      6 => 'svelte',
      7 => 'webpack',
      8 => 'html',
      9 => 'css',
    ),
    'supporting' => 
    array (
      0 => 'tailwind',
      1 => 'css',
      2 => 'sass',
      3 => 'figma',
      4 => 'html',
      5 => 'frontend',
      6 => 'ui',
      7 => 'ux',
      8 => 'git',
    ),
  ),
  'Data Scientist' => 
  array (
    'core' => 
    array (
      0 => 'python',
      1 => 'pandas',
      2 => 'numpy',
      3 => 'spark',
      4 => 'airflow',
      5 => 'bigquery',
      6 => 'tensorflow',
      7 => 'machine learning',
      8 => 'pytorch',
      9 => 'scikit-learn',
    ),
    'supporting' => 
    array (
      0 => 'sql',
      1 => 'etl',
      2 => 'tableau',
      3 => 'statistics',
      4 => 'regression',
      5 => 'nlp',
      6 => 'r',
      7 => 'data visualization',
    ),
  ),
  'Data Analyst' => 
  array (
    'core' => 
    array (
      0 => 'sql',
      1 => 'excel',
      2 => 'tableau',
      3 => 'power bi',
      4 => 'python',
      5 => 'pandas',
      6 => 'data visualization',
      7 => 'reporting',
    ),
    'supporting' => 
    array (
      0 => 'cleaning',
      1 => 'etl',
      2 => 'statistics',
      3 => 'dashboards',
      4 => 'analytical',
      5 => 'queries',
    ),
  ),
  'Civil Engineer' => 
  array (
    'core' => 
    array (
      0 => 'cad',
      1 => 'autocad',
      2 => 'civil 3d',
      3 => 'structural',
      4 => 'infrastructure',
      5 => 'gis',
      6 => 'construction management',
    ),
    'supporting' => 
    array (
      0 => 'inspections',
      1 => 'safety',
      2 => 'excel',
      3 => 'project management',
      4 => 'permits',
      5 => 'design',
    ),
  ),
);

$archetypeEmojis = array (
  'Technology & Engineering' => '⚙️',
  'Marketing, Media & Design' => '🎨',
  'Finance & Accounting' => '📊',
  'Healthcare & Personal Care' => '🩺',
  'Education' => '🍎',
  'Customer Service & Hospitality' => '🤝',
  'Business Operations, HR & Executive' => '📈',
  'Administrative' => '📋',
  'Construction, Manufacturing & Trades' => '🛠️',
  'Government, Legal & Public Safety' => '⚖️',
  'Retail, Sales & Real Estate' => '🛍️',
  'Transportation & Logistics' => '🚚',
);

